#===================================================================
# Spring Boot application configuration for development environment
#===================================================================

#server configuration
server:
  port: ${MyServer.PORT}
#  servlet:
#    context-path: /portfolio_API-0.0.1-SNAPSHOT

spring:
  profiles:
    active: pro
  application:
    name: portfolio_API

    # configuration for file upload limits
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  # Database configuration
  datasource:
    url: jdbc:postgresql://${MyServer.Database.HOST}/${MyServer.Database.DBNAME}
    username: ${MyServer.Database.USER}
    password: "${MyServer.Database.PASS}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  # Email configuration
  mail:
    host: ${MyEmail.mail.host}
    port: ${MyEmail.mail.port}
    username: ${MyEmail.mail.username}
    password: ${MyEmail.mail.password}

    properties:
      mail:
        smtp:
          ssl:
            trust: ${MyEmail.mail.properties.mail.smtp.ssl.trust}
          auth: ${MyEmail.mail.properties.mail.smtp.auth}
          starttls:
            enable: ${MyEmail.mail.properties.mail.smtp.starttls.enable}
          connectiontimeout: ${MyEmail.mail.properties.mail.smtp.connectiontimeout}
          timeout: ${MyEmail.mail.properties.mail.smtp.timeout}
          writetimeout: ${MyEmail.mail.properties.mail.smtp.writetimeout}

  # URL Confirm Register token
  confirm-register-token-url: ${Url.TOKEN_CONFIRM_REGISTER}

  #Store file upload configuration
  uploadsPart: ${StoredFiles.PATH}

  # thymeleaf configuration
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
