MyServer:
  PORT: 8091
  Database:
    HOST: localhost:5432
    USER: postgres
    PASS: "P@ssw0rd()SQL"

MyEmail:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000