#===================================================================
# development Configuration environment
#===================================================================

#Database configuration
MyServer:
  PORT: 8091
  Database:
    HOST: localhost:5432
    DBNAME: Portfolio
    USER: postgres
    PASS: "P@ssw0rd()SQL"


#Link to confirm register token
Url:
  TOKEN_CONFIRM_REGISTER: http://localhost:8091/api/v1/portfolio/auth/confirm?token=

#Store file upload configuration
StoredFiles:
  PATH: /home/portfolio_File/uploads


#Email configuration
MyEmail:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
